var quote = new Array("abet", "able", "acid", "aids", "auto", "axis", "baby", "bail", "bake", "ball", "balm", "band", "bank", "bark", "base", "bath", "bead", "beak", "beam", "bear", "beat", "beau", "beef", "bell", "belt", "bend", "best", "beta", "bias", "bile", "bill", "bind", "bird", "bite", "blot", "blow", "blur", "blue", "boat", "body", "boil", "bold", "bomb", "bond", "bone", "book", "bool", "boon", "boot", "born", "brew", "brik", "brim", "bulb", "bull", "burn", "bury", "bush", "busy", "byte", "cafe", "cage", "cake", "calf", "call", "calm", "camp", "cane", "care", "cart", "case", "cast", "cast", "cave", "ceil", "cell", "chat", "chef", "chew", "cite", "city", "clad", "clap", "claw", "clay", "clip", "club", "clue", "coal", "coat", "cock", "code", "coil", "coin", "coir", "coke", "cold", "comb", "cone", "cook", "cool", "copy", "core", "cork", "corn", "cost", "crab", "crap", "crew", "crop", "crow", "cube", "curd", "cure", "curl", "cute", "czar", "dare", "dark", "data", "date", "dawn", "daze", "dead", "deaf", "deal", "dean", "dear", "debt", "deck", "deed", "deep", "demo", "dent", "dial", "dice", "diet", "dine", "dirt", "disc", "dish", "disk", "diva", "dive", "door", "dose", "dove", "down", "drag", "draw", "drip", "drop", "drug", "drum", "dual", "duck", "duke", "dump");
var meaning = new Array("To urge", "Susceptible to action", "proton donor", "A disease", "self, one's own", "the line generated by a basis vector", "An infant", "A way to release from jail", "cook food with dry heat", "A spherical object", "A chiefly Mediterranean perennial herb", "A simple ungrooved ring", "an institution for receiving, lending, and safeguarding money", "The harsh sound uttered by a dog", "The lowest or bottom part", "The act of soaking or cleansing", "A small, round piece of material", "The horny, projecting structure forming the mandibles of a bird", "A ray of light", "To hold up", "To strike repeatedly", "The boyfriend of a woman or girl", " A full-grown cow, intended for use as meat.", "A hollow metal musical instrument", "A flexible band", "To cause to assume a curved or angular shape", "Surpassing all others in excellence", "The second letter of the Greek alphabet", "unfair direction", "fluid secreted by the liver", " statement of fees or charges", "To tie or secure", "Any warm-blooded egg-laying vertebrate", "To cut, grip, or tear", "A spot or a stain caused by a discoloring substance", "To be in a state of motion", "To make indistinct and hazy in outline", "The hue of that portion of the visible spectrum lying between green and indigo", "A relatively small, usually open craft of a size that might be carried aboard a ship", "The physical part of a person", "To vaporize (a liquid) by the application of heat.", "courageous", "An explosive weapon", "A uniting force", "The dense, semirigid, porous, calcified connective tissue forming the major portion of the skeleton of most vertebrates", "A printed or written literary work", "a playing marble", "A benefit bestowed", "Protective footgear", "Brought into life by birth", "To make (ale or beer) from malt and hops by infusion, boiling, and fermentation", "a Tunisian deep-fried spicy pastry", "The rim or uppermost edge", "An incandescent lamp", "An adult male bovine mammal", "To cause to undergo combustion", "To place in the ground", " A low shrub with many branches", "Engaged in activity", "A sequence of adjacent bits");

var can_play=true;
var display_word="";
var correct_guess=0;
var wrong_guesses=0;
var used_letters="";
var word_selected="";
var correct_count=0;
var wrong_count=0;
var msg="";
var len=quote.length;

var imageList=new Array;
imageList[0]=new Image; imageList[0].src="images/0.png";
imageList[1]=new Image; imageList[1].src="images/1.png";
imageList[2]=new Image; imageList[2].src="images/2.png";
imageList[3]=new Image; imageList[3].src="images/3.png";
imageList[4]=new Image; imageList[4].src="images/4.png";
imageList[5]=new Image; imageList[5].src="images/5.png";
imageList[6]=new Image; imageList[6].src="images/6.png";
function selectWord()
{
 var random_number=Math.round(Math.random()*60); 
 document.myForm.answer.value = quote[random_number];
 word_selected=quote[random_number];
 document.getElementById("Txt").innerHTML = "Meaning: "+meaning[random_number];
 var masked_word=createMask(quote[random_number]);
 document.myForm.displayWord.value=masked_word;
 display_word=masked_word;
 document.myForm.WrongLetters.value="";
 correct_guess=0;
 wrong_guesses=0;
 used_letters="";
}

function createMask(word)
{
 var mask="";
 for(i=0;i<word.length;i++)
 {
  mask+="#";
 }
 return mask;
}

function selectLetter(letter)
{
 letter=letter.toLowerCase();
 if(used_letters.indexOf(letter)!=-1)
 {
  alert(letter+ " is already used");
  return;
 }
 else
 {
  used_letters += letter;
 }
 if(word_selected.indexOf(letter)!=-1)
  {
   var temp_mask=myForm.displayWord.value;
   var pos=0;
   while(word_selected.indexOf(letter,pos)!=-1)
   {
    pos=word_selected.indexOf(letter,pos);
	end=pos+1;
	var start_text=temp_mask.substring(0,pos);
	var end_text=temp_mask.substring(end,temp_mask.length);
	temp_mask=start_text+letter+end_text;
	pos=end;
	correct_guess+=1;
	if(correct_guess==4)
	{
	 correct_count++;
	 correct_guess=0;
	 msg="Congratulation Your Answers is Correct";
	 
	 getScore(msg);
	 return;
	 }
	}
	myForm.displayWord.value=temp_mask;
   } 
	else
	{
	
	 myForm.WrongLetters.value += letter;
	wrong_guesses+=1;
	 document.myForm.counter.value=6-wrong_guesses;
	 slideFuction(wrong_guesses);
	 if(wrong_guesses==6)
	 {
	  wrong_count++;
	  msg="sorry.. No chances left \n \n The Word is " +myForm.answer.value;
	  getScore(msg);
	 }
    }
} 
 function getScore(msg)
 {
  document.scoreform.wonnum.value=correct_count;
  document.scoreform.lostnum.value=wrong_count;
  alert(msg);
  reset();
 } 
 
 function reset()
 {
  document.myForm.WrongLetters.value="";
  used_letters="";
  wrong_guesses=0;
  document.myForm.counter.value=6;
  slideFuction(0);
  selectWord();
 } 
  
  function slideFuction(imageNumber)
  {
   document.slideshow.src=imageList[imageNumber].src;
  } 